import type { ReportResult } from "@/lib/reports.functions";
import collegeLogo from "@/assets/college-logo.jpg.asset.json";
import {
  COLLEGE_FULL_NAME,
  COLLEGE_SHORT_NAME,
  COLLEGE_TAGLINE,
} from "@/components/erp/brand";

/** Branding constants reused by all exports */
const BRAND = {
  institution: COLLEGE_FULL_NAME,
  short: COLLEGE_SHORT_NAME,
  tagline: COLLEGE_TAGLINE,
  watermark: `${COLLEGE_SHORT_NAME} · TVET ERP`,
  primary: [10, 75, 168] as [number, number, number],
  primaryDark: [6, 50, 120] as [number, number, number],
  accentBg: [245, 247, 252] as [number, number, number],
};

export type ExportContext = {
  userName?: string | null;
  userRole?: string | null;
};

const FILTER_LABELS: Record<string, string> = {
  academic_year: "Academic Year",
  semester_id: "Semester",
  department_id: "Department",
  trainer_registry_id: "Trainer",
  module_id: "Module",
  date_from: "Date From",
  date_to: "Date To",
  status: "Status",
  level_id: "Level",
  section_id: "Section",
};
function filterLabel(k: string): string {
  return FILTER_LABELS[k] ?? k.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
}

/** CSV ------------------------------------------------------------------ */
function csvEscape(v: unknown): string {
  if (v === null || v === undefined) return "";
  const s = String(v);
  return /[",\n\r]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

export function reportToCsv(r: ReportResult): string {
  const head = r.columns.map((c) => c.label).join(",");
  const body = r.rows
    .map((row) => r.columns.map((c) => csvEscape(row[c.key])).join(","))
    .join("\n");
  return `${head}\n${body}`;
}

function triggerDownload(filename: string, blob: Blob) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  setTimeout(() => {
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, 0);
}

export function downloadCsv(r: ReportResult) {
  const csv = reportToCsv(r);
  triggerDownload(`${r.key}_${r.generated_at.slice(0, 10)}.csv`, new Blob([csv], { type: "text/csv;charset=utf-8" }));
}

/** XLSX ----------------------------------------------------------------- */
export async function downloadXlsx(r: ReportResult, ctx: ExportContext = {}) {
  const XLSX = await import("xlsx");
  const wb = XLSX.utils.book_new();

  // Main sheet with serial numbers
  const aoa: (string | number)[][] = [["S/N", ...r.columns.map((c) => c.label)]];
  r.rows.forEach((row, i) => {
    aoa.push([i + 1, ...r.columns.map((c) => (row[c.key] as string | number) ?? "")]);
  });
  const ws = XLSX.utils.aoa_to_sheet(aoa);
  ws["!cols"] = [
    { wch: 5 },
    ...r.columns.map((c) => ({
      wch: Math.max(c.label.length + 2, ...r.rows.map((row) => String(row[c.key] ?? "").length + 2)),
    })),
  ];
  ws["!freeze"] = { xSplit: 0, ySplit: 1 } as unknown as never;
  XLSX.utils.book_append_sheet(wb, ws, "Report");

  // Filters + summary sheet
  const meta: (string | number)[][] = [
    ["Institution", BRAND.institution],
    ["Report", r.title],
    ["Generated", new Date(r.generated_at).toLocaleString()],
    ["Generated By", ctx.userName ?? "—"],
    ["Role", ctx.userRole ?? "—"],
  ];
  for (const [k, v] of Object.entries(r.filters)) {
    if (v !== undefined && v !== "") meta.push([`Filter: ${filterLabel(k)}`, String(v)]);
  }
  if (r.summary?.length) {
    meta.push([], ["Summary"]);
    for (const s of r.summary) meta.push([s.label, s.value]);
  }
  XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(meta), "Meta");

  XLSX.writeFile(wb, `${r.key}_${r.generated_at.slice(0, 10)}.xlsx`);
}

/** PDF ------------------------------------------------------------------ */
let _logoDataUrl: string | null = null;
async function getLogoDataUrl(): Promise<string | null> {
  if (_logoDataUrl) return _logoDataUrl;
  try {
    const res = await fetch(collegeLogo.url);
    const blob = await res.blob();
    _logoDataUrl = await new Promise<string>((resolve, reject) => {
      const fr = new FileReader();
      fr.onload = () => resolve(String(fr.result));
      fr.onerror = reject;
      fr.readAsDataURL(blob);
    });
    return _logoDataUrl;
  } catch {
    return null;
  }
}

export async function downloadPdf(r: ReportResult, ctx: ExportContext = {}) {
  const [{ default: jsPDF }, autoTableMod] = await Promise.all([
    import("jspdf"),
    import("jspdf-autotable"),
  ]);
  const autoTable = (autoTableMod as { default: (doc: unknown, opts: unknown) => void }).default;

  const doc = new jsPDF({ orientation: "landscape", unit: "pt", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const logo = await getLogoDataUrl();

  // Filter chips
  const filterChips = Object.entries(r.filters)
    .filter(([, v]) => v !== undefined && v !== "")
    .map(([k, v]) => `${filterLabel(k)}: ${v}`);

  // Header band (drawn on every page via didDrawPage)
  const drawHeader = () => {
    // Branded band
    doc.setFillColor(...BRAND.primary);
    doc.rect(0, 0, pageW, 56, "F");
    if (logo) {
      try { doc.addImage(logo, "JPEG", 24, 10, 36, 36); } catch { /* ignore */ }
    }
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.text(BRAND.institution, 68, 26);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.text(BRAND.tagline, 68, 40);
    doc.setFontSize(9);
    doc.text(`Generated: ${new Date(r.generated_at).toLocaleString()}`, pageW - 24, 26, { align: "right" });
    if (ctx.userName) {
      doc.text(`By: ${ctx.userName}${ctx.userRole ? " · " + ctx.userRole : ""}`, pageW - 24, 40, { align: "right" });
    }

    // Title row
    doc.setTextColor(20, 20, 20);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.text(r.title, 24, 78);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(90, 90, 90);
    const meta: string[] = [];
    if (r.filters.academic_year) meta.push(`Academic Year: ${r.filters.academic_year}`);
    if (r.filters.semester_id) meta.push(`Semester: ${r.filters.semester_id}`);
    if (r.filters.department_id) meta.push(`Department: ${r.filters.department_id}`);
    if (meta.length) doc.text(meta.join("    ·    "), 24, 94);

    // Filter chips line
    const otherChips = filterChips.filter(
      (c) => !c.startsWith("Academic Year:") && !c.startsWith("Semester:") && !c.startsWith("Department:"),
    );
    if (otherChips.length) {
      doc.setTextColor(110, 110, 110);
      doc.text(`Filters: ${otherChips.join("  ·  ")}`, 24, 108);
    }
  };

  const drawWatermark = () => {
    doc.saveGraphicsState?.();
    doc.setTextColor(220, 225, 235);
    doc.setFontSize(54);
    doc.setFont("helvetica", "bold");
    // Diagonal across page
    doc.text(BRAND.watermark, pageW / 2, pageH / 2, {
      align: "center",
      angle: 30,
    });
    doc.restoreGraphicsState?.();
  };

  const drawFooter = (pageNum: number, total: number) => {
    doc.setDrawColor(220);
    doc.setLineWidth(0.5);
    doc.line(24, pageH - 30, pageW - 24, pageH - 30);
    doc.setFontSize(8);
    doc.setTextColor(110, 110, 110);
    doc.setFont("helvetica", "normal");
    doc.text(`${BRAND.short} · TVET ERP`, 24, pageH - 16);
    doc.text(new Date().toLocaleString(), pageW / 2, pageH - 16, { align: "center" });
    doc.text(`Page ${pageNum} of ${total}`, pageW - 24, pageH - 16, { align: "right" });
  };

  // Body table with serial numbers
  const head = [["#", ...r.columns.map((c) => c.label)]];
  const body = r.rows.map((row, i) => [
    String(i + 1),
    ...r.columns.map((c) => String(row[c.key] ?? "")),
  ]);

  autoTable(doc, {
    startY: 120,
    head,
    body,
    styles: { fontSize: 8, cellPadding: 4, overflow: "linebreak", font: "helvetica" },
    headStyles: { fillColor: BRAND.primary, textColor: 255, fontStyle: "bold" },
    alternateRowStyles: { fillColor: BRAND.accentBg },
    columnStyles: { 0: { halign: "right", cellWidth: 26 } },
    margin: { top: 120, left: 24, right: 24, bottom: 40 },
    didDrawPage: () => {
      drawWatermark();
      drawHeader();
    },
  });

  if (r.summary?.length) {
    const finalY = ((doc as unknown as { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? 120) + 18;
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(0);
    doc.text("Summary", 24, finalY);
    autoTable(doc, {
      startY: finalY + 6,
      head: [["Metric", "Value"]],
      body: r.summary.map((s) => [s.label, String(s.value)]),
      styles: { fontSize: 8, cellPadding: 4 },
      headStyles: { fillColor: BRAND.primaryDark, textColor: 255 },
      theme: "grid",
      margin: { left: 24, right: 24, bottom: 40 },
      tableWidth: 320,
      didDrawPage: () => {
        drawWatermark();
        drawHeader();
      },
    });
  }

  // Footer with page numbers (after total page count is known)
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    drawFooter(i, totalPages);
  }

  doc.save(`${r.key}_${r.generated_at.slice(0, 10)}.pdf`);
}

export function openPrintView(reportKey: string, currentSearch: string) {
  const qs = currentSearch.startsWith("?") ? currentSearch : currentSearch ? `?${currentSearch}` : "";
  window.open(`/print/${reportKey}${qs}`, "_blank", "noopener");
}
