/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedStrategicRouteImport } from './routes/_authenticated/strategic'
import { Route as AuthenticatedOperationalRouteImport } from './routes/_authenticated/operational'
import { Route as AuthenticatedGroundRouteImport } from './routes/_authenticated/ground'
import { Route as AuthenticatedStrategicIndexRouteImport } from './routes/_authenticated/strategic/index'
import { Route as AuthenticatedOperationalIndexRouteImport } from './routes/_authenticated/operational/index'
import { Route as AuthenticatedGroundIndexRouteImport } from './routes/_authenticated/ground/index'
import { Route as AuthenticatedStrategicVenuesRouteImport } from './routes/_authenticated/strategic/venues'
import { Route as AuthenticatedStrategicUsersRouteImport } from './routes/_authenticated/strategic/users'
import { Route as AuthenticatedStrategicTrainersRouteImport } from './routes/_authenticated/strategic/trainers'
import { Route as AuthenticatedStrategicStudentsRouteImport } from './routes/_authenticated/strategic/students'
import { Route as AuthenticatedStrategicSettingsRouteImport } from './routes/_authenticated/strategic/settings'
import { Route as AuthenticatedStrategicSemestersRouteImport } from './routes/_authenticated/strategic/semesters'
import { Route as AuthenticatedStrategicSectionsRouteImport } from './routes/_authenticated/strategic/sections'
import { Route as AuthenticatedStrategicModulesRouteImport } from './routes/_authenticated/strategic/modules'
import { Route as AuthenticatedStrategicLevelsRouteImport } from './routes/_authenticated/strategic/levels'
import { Route as AuthenticatedStrategicDepartmentsRouteImport } from './routes/_authenticated/strategic/departments'
import { Route as AuthenticatedStrategicDepartmentHeadsRouteImport } from './routes/_authenticated/strategic/department-heads'
import { Route as AuthenticatedStrategicAuditRouteImport } from './routes/_authenticated/strategic/audit'
import { Route as AuthenticatedStrategicApprovalsRouteImport } from './routes/_authenticated/strategic/approvals'
import { Route as AuthenticatedOperationalLiveMonitorRouteImport } from './routes/_authenticated/operational/live-monitor'
import { Route as AuthenticatedGroundScheduleIdRouteImport } from './routes/_authenticated/ground/$scheduleId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStrategicRoute = AuthenticatedStrategicRouteImport.update({
  id: '/strategic',
  path: '/strategic',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOperationalRoute =
  AuthenticatedOperationalRouteImport.update({
    id: '/operational',
    path: '/operational',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGroundRoute = AuthenticatedGroundRouteImport.update({
  id: '/ground',
  path: '/ground',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStrategicIndexRoute =
  AuthenticatedStrategicIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStrategicRoute,
  } as any)
const AuthenticatedOperationalIndexRoute =
  AuthenticatedOperationalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOperationalRoute,
  } as any)
const AuthenticatedGroundIndexRoute =
  AuthenticatedGroundIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedGroundRoute,
  } as any)
const AuthenticatedStrategicVenuesRoute =
  AuthenticatedStrategicVenuesRouteImport.update({
    id: '/venues',
    path: '/venues',
    getParentRoute: () => AuthenticatedStrategicRoute,
  } as any)
const AuthenticatedStrategicUsersRoute =
  AuthenticatedStrategicUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedStrategicRoute,
  } as any)
const AuthenticatedStrategicTrainersRoute =
  AuthenticatedStrategicTrainersRouteImport.update({
    id: '/trainers',
    path: '/trainers',
    getParentRoute: () => AuthenticatedStrategicRoute,
  } as any)
const AuthenticatedStrategicStudentsRoute =
  AuthenticatedStrategicStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => AuthenticatedStrategicRoute,
  } as any)
const AuthenticatedStrategicSettingsRoute =
  AuthenticatedStrategicSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedStrategicRoute,
  } as any)
const AuthenticatedStrategicSemestersRoute =
  AuthenticatedStrategicSemestersRouteImport.update({
    id: '/semesters',
    path: '/semesters',
    getParentRoute: () => AuthenticatedStrategicRoute,
  } as any)
const AuthenticatedStrategicSectionsRoute =
  AuthenticatedStrategicSectionsRouteImport.update({
    id: '/sections',
    path: '/sections',
    getParentRoute: () => AuthenticatedStrategicRoute,
  } as any)
const AuthenticatedStrategicModulesRoute =
  AuthenticatedStrategicModulesRouteImport.update({
    id: '/modules',
    path: '/modules',
    getParentRoute: () => AuthenticatedStrategicRoute,
  } as any)
const AuthenticatedStrategicLevelsRoute =
  AuthenticatedStrategicLevelsRouteImport.update({
    id: '/levels',
    path: '/levels',
    getParentRoute: () => AuthenticatedStrategicRoute,
  } as any)
const AuthenticatedStrategicDepartmentsRoute =
  AuthenticatedStrategicDepartmentsRouteImport.update({
    id: '/departments',
    path: '/departments',
    getParentRoute: () => AuthenticatedStrategicRoute,
  } as any)
const AuthenticatedStrategicDepartmentHeadsRoute =
  AuthenticatedStrategicDepartmentHeadsRouteImport.update({
    id: '/department-heads',
    path: '/department-heads',
    getParentRoute: () => AuthenticatedStrategicRoute,
  } as any)
const AuthenticatedStrategicAuditRoute =
  AuthenticatedStrategicAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => AuthenticatedStrategicRoute,
  } as any)
const AuthenticatedStrategicApprovalsRoute =
  AuthenticatedStrategicApprovalsRouteImport.update({
    id: '/approvals',
    path: '/approvals',
    getParentRoute: () => AuthenticatedStrategicRoute,
  } as any)
const AuthenticatedOperationalLiveMonitorRoute =
  AuthenticatedOperationalLiveMonitorRouteImport.update({
    id: '/live-monitor',
    path: '/live-monitor',
    getParentRoute: () => AuthenticatedOperationalRoute,
  } as any)
const AuthenticatedGroundScheduleIdRoute =
  AuthenticatedGroundScheduleIdRouteImport.update({
    id: '/$scheduleId',
    path: '/$scheduleId',
    getParentRoute: () => AuthenticatedGroundRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ground': typeof AuthenticatedGroundRouteWithChildren
  '/operational': typeof AuthenticatedOperationalRouteWithChildren
  '/strategic': typeof AuthenticatedStrategicRouteWithChildren
  '/ground/$scheduleId': typeof AuthenticatedGroundScheduleIdRoute
  '/operational/live-monitor': typeof AuthenticatedOperationalLiveMonitorRoute
  '/strategic/approvals': typeof AuthenticatedStrategicApprovalsRoute
  '/strategic/audit': typeof AuthenticatedStrategicAuditRoute
  '/strategic/department-heads': typeof AuthenticatedStrategicDepartmentHeadsRoute
  '/strategic/departments': typeof AuthenticatedStrategicDepartmentsRoute
  '/strategic/levels': typeof AuthenticatedStrategicLevelsRoute
  '/strategic/modules': typeof AuthenticatedStrategicModulesRoute
  '/strategic/sections': typeof AuthenticatedStrategicSectionsRoute
  '/strategic/semesters': typeof AuthenticatedStrategicSemestersRoute
  '/strategic/settings': typeof AuthenticatedStrategicSettingsRoute
  '/strategic/students': typeof AuthenticatedStrategicStudentsRoute
  '/strategic/trainers': typeof AuthenticatedStrategicTrainersRoute
  '/strategic/users': typeof AuthenticatedStrategicUsersRoute
  '/strategic/venues': typeof AuthenticatedStrategicVenuesRoute
  '/ground/': typeof AuthenticatedGroundIndexRoute
  '/operational/': typeof AuthenticatedOperationalIndexRoute
  '/strategic/': typeof AuthenticatedStrategicIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ground/$scheduleId': typeof AuthenticatedGroundScheduleIdRoute
  '/operational/live-monitor': typeof AuthenticatedOperationalLiveMonitorRoute
  '/strategic/approvals': typeof AuthenticatedStrategicApprovalsRoute
  '/strategic/audit': typeof AuthenticatedStrategicAuditRoute
  '/strategic/department-heads': typeof AuthenticatedStrategicDepartmentHeadsRoute
  '/strategic/departments': typeof AuthenticatedStrategicDepartmentsRoute
  '/strategic/levels': typeof AuthenticatedStrategicLevelsRoute
  '/strategic/modules': typeof AuthenticatedStrategicModulesRoute
  '/strategic/sections': typeof AuthenticatedStrategicSectionsRoute
  '/strategic/semesters': typeof AuthenticatedStrategicSemestersRoute
  '/strategic/settings': typeof AuthenticatedStrategicSettingsRoute
  '/strategic/students': typeof AuthenticatedStrategicStudentsRoute
  '/strategic/trainers': typeof AuthenticatedStrategicTrainersRoute
  '/strategic/users': typeof AuthenticatedStrategicUsersRoute
  '/strategic/venues': typeof AuthenticatedStrategicVenuesRoute
  '/ground': typeof AuthenticatedGroundIndexRoute
  '/operational': typeof AuthenticatedOperationalIndexRoute
  '/strategic': typeof AuthenticatedStrategicIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/ground': typeof AuthenticatedGroundRouteWithChildren
  '/_authenticated/operational': typeof AuthenticatedOperationalRouteWithChildren
  '/_authenticated/strategic': typeof AuthenticatedStrategicRouteWithChildren
  '/_authenticated/ground/$scheduleId': typeof AuthenticatedGroundScheduleIdRoute
  '/_authenticated/operational/live-monitor': typeof AuthenticatedOperationalLiveMonitorRoute
  '/_authenticated/strategic/approvals': typeof AuthenticatedStrategicApprovalsRoute
  '/_authenticated/strategic/audit': typeof AuthenticatedStrategicAuditRoute
  '/_authenticated/strategic/department-heads': typeof AuthenticatedStrategicDepartmentHeadsRoute
  '/_authenticated/strategic/departments': typeof AuthenticatedStrategicDepartmentsRoute
  '/_authenticated/strategic/levels': typeof AuthenticatedStrategicLevelsRoute
  '/_authenticated/strategic/modules': typeof AuthenticatedStrategicModulesRoute
  '/_authenticated/strategic/sections': typeof AuthenticatedStrategicSectionsRoute
  '/_authenticated/strategic/semesters': typeof AuthenticatedStrategicSemestersRoute
  '/_authenticated/strategic/settings': typeof AuthenticatedStrategicSettingsRoute
  '/_authenticated/strategic/students': typeof AuthenticatedStrategicStudentsRoute
  '/_authenticated/strategic/trainers': typeof AuthenticatedStrategicTrainersRoute
  '/_authenticated/strategic/users': typeof AuthenticatedStrategicUsersRoute
  '/_authenticated/strategic/venues': typeof AuthenticatedStrategicVenuesRoute
  '/_authenticated/ground/': typeof AuthenticatedGroundIndexRoute
  '/_authenticated/operational/': typeof AuthenticatedOperationalIndexRoute
  '/_authenticated/strategic/': typeof AuthenticatedStrategicIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/ground'
    | '/operational'
    | '/strategic'
    | '/ground/$scheduleId'
    | '/operational/live-monitor'
    | '/strategic/approvals'
    | '/strategic/audit'
    | '/strategic/department-heads'
    | '/strategic/departments'
    | '/strategic/levels'
    | '/strategic/modules'
    | '/strategic/sections'
    | '/strategic/semesters'
    | '/strategic/settings'
    | '/strategic/students'
    | '/strategic/trainers'
    | '/strategic/users'
    | '/strategic/venues'
    | '/ground/'
    | '/operational/'
    | '/strategic/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/ground/$scheduleId'
    | '/operational/live-monitor'
    | '/strategic/approvals'
    | '/strategic/audit'
    | '/strategic/department-heads'
    | '/strategic/departments'
    | '/strategic/levels'
    | '/strategic/modules'
    | '/strategic/sections'
    | '/strategic/semesters'
    | '/strategic/settings'
    | '/strategic/students'
    | '/strategic/trainers'
    | '/strategic/users'
    | '/strategic/venues'
    | '/ground'
    | '/operational'
    | '/strategic'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/ground'
    | '/_authenticated/operational'
    | '/_authenticated/strategic'
    | '/_authenticated/ground/$scheduleId'
    | '/_authenticated/operational/live-monitor'
    | '/_authenticated/strategic/approvals'
    | '/_authenticated/strategic/audit'
    | '/_authenticated/strategic/department-heads'
    | '/_authenticated/strategic/departments'
    | '/_authenticated/strategic/levels'
    | '/_authenticated/strategic/modules'
    | '/_authenticated/strategic/sections'
    | '/_authenticated/strategic/semesters'
    | '/_authenticated/strategic/settings'
    | '/_authenticated/strategic/students'
    | '/_authenticated/strategic/trainers'
    | '/_authenticated/strategic/users'
    | '/_authenticated/strategic/venues'
    | '/_authenticated/ground/'
    | '/_authenticated/operational/'
    | '/_authenticated/strategic/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/strategic': {
      id: '/_authenticated/strategic'
      path: '/strategic'
      fullPath: '/strategic'
      preLoaderRoute: typeof AuthenticatedStrategicRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/operational': {
      id: '/_authenticated/operational'
      path: '/operational'
      fullPath: '/operational'
      preLoaderRoute: typeof AuthenticatedOperationalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ground': {
      id: '/_authenticated/ground'
      path: '/ground'
      fullPath: '/ground'
      preLoaderRoute: typeof AuthenticatedGroundRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/strategic/': {
      id: '/_authenticated/strategic/'
      path: '/'
      fullPath: '/strategic/'
      preLoaderRoute: typeof AuthenticatedStrategicIndexRouteImport
      parentRoute: typeof AuthenticatedStrategicRoute
    }
    '/_authenticated/operational/': {
      id: '/_authenticated/operational/'
      path: '/'
      fullPath: '/operational/'
      preLoaderRoute: typeof AuthenticatedOperationalIndexRouteImport
      parentRoute: typeof AuthenticatedOperationalRoute
    }
    '/_authenticated/ground/': {
      id: '/_authenticated/ground/'
      path: '/'
      fullPath: '/ground/'
      preLoaderRoute: typeof AuthenticatedGroundIndexRouteImport
      parentRoute: typeof AuthenticatedGroundRoute
    }
    '/_authenticated/strategic/venues': {
      id: '/_authenticated/strategic/venues'
      path: '/venues'
      fullPath: '/strategic/venues'
      preLoaderRoute: typeof AuthenticatedStrategicVenuesRouteImport
      parentRoute: typeof AuthenticatedStrategicRoute
    }
    '/_authenticated/strategic/users': {
      id: '/_authenticated/strategic/users'
      path: '/users'
      fullPath: '/strategic/users'
      preLoaderRoute: typeof AuthenticatedStrategicUsersRouteImport
      parentRoute: typeof AuthenticatedStrategicRoute
    }
    '/_authenticated/strategic/trainers': {
      id: '/_authenticated/strategic/trainers'
      path: '/trainers'
      fullPath: '/strategic/trainers'
      preLoaderRoute: typeof AuthenticatedStrategicTrainersRouteImport
      parentRoute: typeof AuthenticatedStrategicRoute
    }
    '/_authenticated/strategic/students': {
      id: '/_authenticated/strategic/students'
      path: '/students'
      fullPath: '/strategic/students'
      preLoaderRoute: typeof AuthenticatedStrategicStudentsRouteImport
      parentRoute: typeof AuthenticatedStrategicRoute
    }
    '/_authenticated/strategic/settings': {
      id: '/_authenticated/strategic/settings'
      path: '/settings'
      fullPath: '/strategic/settings'
      preLoaderRoute: typeof AuthenticatedStrategicSettingsRouteImport
      parentRoute: typeof AuthenticatedStrategicRoute
    }
    '/_authenticated/strategic/semesters': {
      id: '/_authenticated/strategic/semesters'
      path: '/semesters'
      fullPath: '/strategic/semesters'
      preLoaderRoute: typeof AuthenticatedStrategicSemestersRouteImport
      parentRoute: typeof AuthenticatedStrategicRoute
    }
    '/_authenticated/strategic/sections': {
      id: '/_authenticated/strategic/sections'
      path: '/sections'
      fullPath: '/strategic/sections'
      preLoaderRoute: typeof AuthenticatedStrategicSectionsRouteImport
      parentRoute: typeof AuthenticatedStrategicRoute
    }
    '/_authenticated/strategic/modules': {
      id: '/_authenticated/strategic/modules'
      path: '/modules'
      fullPath: '/strategic/modules'
      preLoaderRoute: typeof AuthenticatedStrategicModulesRouteImport
      parentRoute: typeof AuthenticatedStrategicRoute
    }
    '/_authenticated/strategic/levels': {
      id: '/_authenticated/strategic/levels'
      path: '/levels'
      fullPath: '/strategic/levels'
      preLoaderRoute: typeof AuthenticatedStrategicLevelsRouteImport
      parentRoute: typeof AuthenticatedStrategicRoute
    }
    '/_authenticated/strategic/departments': {
      id: '/_authenticated/strategic/departments'
      path: '/departments'
      fullPath: '/strategic/departments'
      preLoaderRoute: typeof AuthenticatedStrategicDepartmentsRouteImport
      parentRoute: typeof AuthenticatedStrategicRoute
    }
    '/_authenticated/strategic/department-heads': {
      id: '/_authenticated/strategic/department-heads'
      path: '/department-heads'
      fullPath: '/strategic/department-heads'
      preLoaderRoute: typeof AuthenticatedStrategicDepartmentHeadsRouteImport
      parentRoute: typeof AuthenticatedStrategicRoute
    }
    '/_authenticated/strategic/audit': {
      id: '/_authenticated/strategic/audit'
      path: '/audit'
      fullPath: '/strategic/audit'
      preLoaderRoute: typeof AuthenticatedStrategicAuditRouteImport
      parentRoute: typeof AuthenticatedStrategicRoute
    }
    '/_authenticated/strategic/approvals': {
      id: '/_authenticated/strategic/approvals'
      path: '/approvals'
      fullPath: '/strategic/approvals'
      preLoaderRoute: typeof AuthenticatedStrategicApprovalsRouteImport
      parentRoute: typeof AuthenticatedStrategicRoute
    }
    '/_authenticated/operational/live-monitor': {
      id: '/_authenticated/operational/live-monitor'
      path: '/live-monitor'
      fullPath: '/operational/live-monitor'
      preLoaderRoute: typeof AuthenticatedOperationalLiveMonitorRouteImport
      parentRoute: typeof AuthenticatedOperationalRoute
    }
    '/_authenticated/ground/$scheduleId': {
      id: '/_authenticated/ground/$scheduleId'
      path: '/$scheduleId'
      fullPath: '/ground/$scheduleId'
      preLoaderRoute: typeof AuthenticatedGroundScheduleIdRouteImport
      parentRoute: typeof AuthenticatedGroundRoute
    }
  }
}

interface AuthenticatedGroundRouteChildren {
  AuthenticatedGroundScheduleIdRoute: typeof AuthenticatedGroundScheduleIdRoute
  AuthenticatedGroundIndexRoute: typeof AuthenticatedGroundIndexRoute
}

const AuthenticatedGroundRouteChildren: AuthenticatedGroundRouteChildren = {
  AuthenticatedGroundScheduleIdRoute: AuthenticatedGroundScheduleIdRoute,
  AuthenticatedGroundIndexRoute: AuthenticatedGroundIndexRoute,
}

const AuthenticatedGroundRouteWithChildren =
  AuthenticatedGroundRoute._addFileChildren(AuthenticatedGroundRouteChildren)

interface AuthenticatedOperationalRouteChildren {
  AuthenticatedOperationalLiveMonitorRoute: typeof AuthenticatedOperationalLiveMonitorRoute
  AuthenticatedOperationalIndexRoute: typeof AuthenticatedOperationalIndexRoute
}

const AuthenticatedOperationalRouteChildren: AuthenticatedOperationalRouteChildren =
  {
    AuthenticatedOperationalLiveMonitorRoute:
      AuthenticatedOperationalLiveMonitorRoute,
    AuthenticatedOperationalIndexRoute: AuthenticatedOperationalIndexRoute,
  }

const AuthenticatedOperationalRouteWithChildren =
  AuthenticatedOperationalRoute._addFileChildren(
    AuthenticatedOperationalRouteChildren,
  )

interface AuthenticatedStrategicRouteChildren {
  AuthenticatedStrategicApprovalsRoute: typeof AuthenticatedStrategicApprovalsRoute
  AuthenticatedStrategicAuditRoute: typeof AuthenticatedStrategicAuditRoute
  AuthenticatedStrategicDepartmentHeadsRoute: typeof AuthenticatedStrategicDepartmentHeadsRoute
  AuthenticatedStrategicDepartmentsRoute: typeof AuthenticatedStrategicDepartmentsRoute
  AuthenticatedStrategicLevelsRoute: typeof AuthenticatedStrategicLevelsRoute
  AuthenticatedStrategicModulesRoute: typeof AuthenticatedStrategicModulesRoute
  AuthenticatedStrategicSectionsRoute: typeof AuthenticatedStrategicSectionsRoute
  AuthenticatedStrategicSemestersRoute: typeof AuthenticatedStrategicSemestersRoute
  AuthenticatedStrategicSettingsRoute: typeof AuthenticatedStrategicSettingsRoute
  AuthenticatedStrategicStudentsRoute: typeof AuthenticatedStrategicStudentsRoute
  AuthenticatedStrategicTrainersRoute: typeof AuthenticatedStrategicTrainersRoute
  AuthenticatedStrategicUsersRoute: typeof AuthenticatedStrategicUsersRoute
  AuthenticatedStrategicVenuesRoute: typeof AuthenticatedStrategicVenuesRoute
  AuthenticatedStrategicIndexRoute: typeof AuthenticatedStrategicIndexRoute
}

const AuthenticatedStrategicRouteChildren: AuthenticatedStrategicRouteChildren =
  {
    AuthenticatedStrategicApprovalsRoute: AuthenticatedStrategicApprovalsRoute,
    AuthenticatedStrategicAuditRoute: AuthenticatedStrategicAuditRoute,
    AuthenticatedStrategicDepartmentHeadsRoute:
      AuthenticatedStrategicDepartmentHeadsRoute,
    AuthenticatedStrategicDepartmentsRoute:
      AuthenticatedStrategicDepartmentsRoute,
    AuthenticatedStrategicLevelsRoute: AuthenticatedStrategicLevelsRoute,
    AuthenticatedStrategicModulesRoute: AuthenticatedStrategicModulesRoute,
    AuthenticatedStrategicSectionsRoute: AuthenticatedStrategicSectionsRoute,
    AuthenticatedStrategicSemestersRoute: AuthenticatedStrategicSemestersRoute,
    AuthenticatedStrategicSettingsRoute: AuthenticatedStrategicSettingsRoute,
    AuthenticatedStrategicStudentsRoute: AuthenticatedStrategicStudentsRoute,
    AuthenticatedStrategicTrainersRoute: AuthenticatedStrategicTrainersRoute,
    AuthenticatedStrategicUsersRoute: AuthenticatedStrategicUsersRoute,
    AuthenticatedStrategicVenuesRoute: AuthenticatedStrategicVenuesRoute,
    AuthenticatedStrategicIndexRoute: AuthenticatedStrategicIndexRoute,
  }

const AuthenticatedStrategicRouteWithChildren =
  AuthenticatedStrategicRoute._addFileChildren(
    AuthenticatedStrategicRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedGroundRoute: typeof AuthenticatedGroundRouteWithChildren
  AuthenticatedOperationalRoute: typeof AuthenticatedOperationalRouteWithChildren
  AuthenticatedStrategicRoute: typeof AuthenticatedStrategicRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedGroundRoute: AuthenticatedGroundRouteWithChildren,
  AuthenticatedOperationalRoute: AuthenticatedOperationalRouteWithChildren,
  AuthenticatedStrategicRoute: AuthenticatedStrategicRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
