/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedStrategicRouteImport } from './routes/_authenticated/strategic'
import { Route as AuthenticatedOperationalRouteImport } from './routes/_authenticated/operational'
import { Route as AuthenticatedGroundRouteImport } from './routes/_authenticated/ground'
import { Route as AuthenticatedOperationalIndexRouteImport } from './routes/_authenticated/operational/index'
import { Route as AuthenticatedGroundIndexRouteImport } from './routes/_authenticated/ground/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStrategicRoute = AuthenticatedStrategicRouteImport.update({
  id: '/strategic',
  path: '/strategic',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOperationalRoute =
  AuthenticatedOperationalRouteImport.update({
    id: '/operational',
    path: '/operational',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGroundRoute = AuthenticatedGroundRouteImport.update({
  id: '/ground',
  path: '/ground',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOperationalIndexRoute =
  AuthenticatedOperationalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOperationalRoute,
  } as any)
const AuthenticatedGroundIndexRoute =
  AuthenticatedGroundIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedGroundRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ground': typeof AuthenticatedGroundRouteWithChildren
  '/operational': typeof AuthenticatedOperationalRouteWithChildren
  '/strategic': typeof AuthenticatedStrategicRoute
  '/ground/': typeof AuthenticatedGroundIndexRoute
  '/operational/': typeof AuthenticatedOperationalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/strategic': typeof AuthenticatedStrategicRoute
  '/ground': typeof AuthenticatedGroundIndexRoute
  '/operational': typeof AuthenticatedOperationalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/ground': typeof AuthenticatedGroundRouteWithChildren
  '/_authenticated/operational': typeof AuthenticatedOperationalRouteWithChildren
  '/_authenticated/strategic': typeof AuthenticatedStrategicRoute
  '/_authenticated/ground/': typeof AuthenticatedGroundIndexRoute
  '/_authenticated/operational/': typeof AuthenticatedOperationalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/ground'
    | '/operational'
    | '/strategic'
    | '/ground/'
    | '/operational/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/strategic' | '/ground' | '/operational'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/ground'
    | '/_authenticated/operational'
    | '/_authenticated/strategic'
    | '/_authenticated/ground/'
    | '/_authenticated/operational/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/strategic': {
      id: '/_authenticated/strategic'
      path: '/strategic'
      fullPath: '/strategic'
      preLoaderRoute: typeof AuthenticatedStrategicRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/operational': {
      id: '/_authenticated/operational'
      path: '/operational'
      fullPath: '/operational'
      preLoaderRoute: typeof AuthenticatedOperationalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ground': {
      id: '/_authenticated/ground'
      path: '/ground'
      fullPath: '/ground'
      preLoaderRoute: typeof AuthenticatedGroundRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/operational/': {
      id: '/_authenticated/operational/'
      path: '/'
      fullPath: '/operational/'
      preLoaderRoute: typeof AuthenticatedOperationalIndexRouteImport
      parentRoute: typeof AuthenticatedOperationalRoute
    }
    '/_authenticated/ground/': {
      id: '/_authenticated/ground/'
      path: '/'
      fullPath: '/ground/'
      preLoaderRoute: typeof AuthenticatedGroundIndexRouteImport
      parentRoute: typeof AuthenticatedGroundRoute
    }
  }
}

interface AuthenticatedGroundRouteChildren {
  AuthenticatedGroundIndexRoute: typeof AuthenticatedGroundIndexRoute
}

const AuthenticatedGroundRouteChildren: AuthenticatedGroundRouteChildren = {
  AuthenticatedGroundIndexRoute: AuthenticatedGroundIndexRoute,
}

const AuthenticatedGroundRouteWithChildren =
  AuthenticatedGroundRoute._addFileChildren(AuthenticatedGroundRouteChildren)

interface AuthenticatedOperationalRouteChildren {
  AuthenticatedOperationalIndexRoute: typeof AuthenticatedOperationalIndexRoute
}

const AuthenticatedOperationalRouteChildren: AuthenticatedOperationalRouteChildren =
  {
    AuthenticatedOperationalIndexRoute: AuthenticatedOperationalIndexRoute,
  }

const AuthenticatedOperationalRouteWithChildren =
  AuthenticatedOperationalRoute._addFileChildren(
    AuthenticatedOperationalRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedGroundRoute: typeof AuthenticatedGroundRouteWithChildren
  AuthenticatedOperationalRoute: typeof AuthenticatedOperationalRouteWithChildren
  AuthenticatedStrategicRoute: typeof AuthenticatedStrategicRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedGroundRoute: AuthenticatedGroundRouteWithChildren,
  AuthenticatedOperationalRoute: AuthenticatedOperationalRouteWithChildren,
  AuthenticatedStrategicRoute: AuthenticatedStrategicRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
