// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    const { data } = await supabase.auth.getSession()
    const token = data.session?.access_token
    if (!token) {
      // Fail fast on the client so we don't hit the server with no Bearer
      // header — that path returns 500 + blank screen instead of a clean error.
      throw new Error('Not authenticated')
    }
    return next({
      headers: { Authorization: `Bearer ${token}` },
    })
  },
)
